### ISSUE TITLE
Microevent on bower?

### ISSUE THREAD

**Issue by nicbell** [jeromeetienne/microevent.js#34]
It would be great to have microevent on bower.

**Comment by jeromeetienne** [comment]
nice idea! thanks! 

<img width="1119" alt="screen shot 2015-07-03 at 19 59 07" src="https://cloud.githubusercontent.com/assets/252962/8503862/08f12bb4-21be-11e5-972a-f60499b4f845.png">

done

**Comment by shariffy** [comment]
Any idea why it's not showing up in [the search](http://bower.io/search/?q=microevent)?

That omission caused me to be use a fork, and that's not right.

Is it because there's no `bower.json`? See #35.
